### ISSUE TITLE
PHP7 branch build on Win32 VC14

### ISSUE THREAD

**Issue by wagy** [phpv8/v8js#194]
Hi,
1. build v8 with using VS 2015,  everything looks OK.
2. copied the libs and headers to deps in PHP build tree   V7.0.1
3. copied the v8js branch PHP7 to ext folder in PHP build tree
4. configure  --disable-all --enable-cli --enable-cli-win32  --with-v8js
5. nmake
result 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\chrono(778): warning C4091: "__forceinline ": Ignoriert auf der linken Seite von "int", wenn keine Variable deklariert wurde (Quelldatei wird kompiliert ext\v8js\v8js.cc)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\chrono(778): error C2143: Syntaxfehler: Es fehlt ";" vor "namespace" (Quelldatei wird kompiliert ext\v8js\v8js.cc)
....
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe"": Rückgabe-Code "0x2"

looks like a problem with inline name space  ?
chrono
..
774		return (_Xt);
775		}
776	
777		// duration LITERALS
778	inline namespace literals {
779	inline namespace chrono_literals {
780	inline _CONST_FUN chrono::hours operator "" h(unsigned long long _Val)
..

**Comment by stesie** [comment]
Hi,

could you please try moving the `#include <chrono>` line in `php_v8js_macros.h` right above the `extern "C"` line and then simply try again?  I suppose that php defines a macro named `inline`, which replaces the keyword `inline` in front of the `namespace` keyword (to something that isn't valid at that particular position).

I haven't yet tried that out as accessing a Windows box always is a bit of a hazzle; but let me know if that still doesn't work ... then I'll go and organize one :)

cheers
~stesie

**Comment by wagy** [comment]
Hi

yes this error is fixed bad now there is a other problem.
Now they include abs and also extern "C"  abs 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(17): error C2894: Vorlagen können nicht mit "C"-Bindung deklariert werden (Quelldatei wird kompiliert ext\v8js\v8js_array_access.cc)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(35): error C2733: "abs" : Zweite C-Bindung fr berladene Funktion nicht zul„ssig (Quelldatei wird kompiliert ext\v8js\v8js_array_access.cc)
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt\stdlib.h(286): note: Siehe Deklaration von "abs" (Quelldatei wird kompiliert ext\v8js\v8js_array_access.cc)
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath(40): error C2733: "pow" : Zweite C-Bindung fr berladene Funktion nicht zul„ssig (Quelldatei wird kompiliert ext\v8js\v8js_array_access.cc)
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt\math.h(483): note: Siehe Deklaration von "pow" (Quelldatei wird kompiliert ext\v8js\v8js_array_access.cc)
.....

cheers
walter

**Comment by stesie** [comment]
hmm, I'll rent a box on Amazon's EC2 and then have a look ...

**Comment by stesie** [comment]
The php7 branch now compiles fine, but V8Js still has some issues regarding the test suite (opposed to using it under GNU/Linux).  What seems especially strange to me: it crashes if you require a three modules in a row :(

... and time/memory limit doesn't work neither.

everything else seems ok

**Comment by stesie** [comment]
Ok, so the problems mentioned before all relate to V8Js not initializing v8::Platform as needed.  This complicates compilation a bit, but makes all tests pass :-)

Actually there were three tests left red, after initializing platform as needed, two of them caused by \r\n vs. \n differences and another one by providing error reporting in a slightly different order.

Besides that
* there is now a continuous integration system (AppVeyor) set up for V8Js on Windows: https://ci.appveyor.com/project/stesie/v8js
* builds are automatically triggered on every pull request and merge to the php7 branch
* the README.md file now shows a seperate build badge for Windows :-)
* the `php_v8js.dll` resulting from the build is pushed to a S3 bucket and available from https://s3.amazonaws.com/win-phpv8/v8js_vc14_php7_ts.zip (x86 build with thread safety)

So in order to use V8Js on Windows you can now
* install VC14 runtime
* use x86 TS build from http://windows.php.net/download/
* unpack https://s3.amazonaws.com/win-phpv8/v8js_vc14_php7_ts.zip right beside php.exe

... and you're ready to go :-)

**Comment by wagy** [comment]
Thank you :-)
