### ISSUE TITLE
[V8 built with gn] configure: error: could not determine libv8 version

### ISSUE THREAD

**Issue by temuri416** [phpv8/v8js#269]
Hello there again,

Can't compile the extension:

```
checking for V8 Javascript Engine... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for C standard version... c++11
checking how to allow c++11 narrowing... -Wno-narrowing
checking for V8 version... NONE
configure: error: could not determine libv8 version
```

PHP5 V8 was compiled successfully following instructions at https://github.com/v8/v8/wiki/Building%20with%20GN

In #139 everything worked after I manually copied _.so files to /usr/lib/x86_64-linux-gnu/, but *_gn*\* build is entirely different and I cannot find output *.so files anywhere.

Have you tested compiling your extension against V8 built with gn? What steps could I be missing?

Thanks!

**Comment by temuri416** [comment]
ok, I got the .so files by adding "is_component_build = true" to out.gn/x64.release/args.gn... But now I get this error:

```
checking for V8 version... 5.6.0
checking for libv8_libplatform.a... not found
configure: error: Please provide libv8_libplatform.a next to the libv8.so, see README.md for details
``

Any clue?

**Comment by temuri416** [comment]
another update...

after compiling v8 with **"is_component_build = true"** I ran the following commands:

```
cp out/gn/lib*.so /usr/lib/ && cp -R include/* /usr/include
cd out.gn/x64.release
ar rcsDT libv8_libplatform.a v8_libplatform/*.o
echo -e "create /usr/lib/libv8_libplatform.a\naddlib /usr/local/src/v8/out.gn/x64.release/obj/libv8_libplatform.a\nsave\nend" | sudo ar -M
```

After that v8js did compile with:

```
phpize
./configure
make && make install
```

However, `php -m` is reporting:

```
/usr/lib/libv8.so: undefined symbol: _ZTVN6icu_5613UnicodeStringE in Unknown on line 0
```

Crap... :(

**Comment by temuri416** [comment]
sorry for spamming, but this may save others a few hours :-)

I finally got every working. The "undefined symbol" problem can be circumvented by supplying "v8_enable_i18n_support = false" in out.gn/x64.release/args.gn. It looks now as:

```
is_debug = false
target_cpu = "x64"
is_component_build = true
v8_enable_i18n_support = false
```

Not sure if this is really required, but I also updated `out.gn/x64.release/v8_build_config.json` with: `"v8_enable_i18n_support": false`.

After it compiles run commands from my previous comments and then v8js will build and report v8 version >5.6.

At this point I could not figure out how to do `gn` build to use system icu libraries. This link https://github.com/v8/v8/wiki/i18n%20support has instructions that are only for gyp build.

That's it.

**Comment by stesie** [comment]
Hey, sorry for not answering earlier. Unfortunately I was too busy lately ...

anyways, thank you soooo much for figuring that out already :) I don't think we need a solution to link against system icu libraries ... yet completely disabling i18n is a bummer also. I'd appreciate if we can make it work with third-party-icu as before

**Comment by FullstackJack** [comment]
Also having trouble generating a libv8_libplatform.a file on a Ubuntu vagrant box. I have been trying with the LINUX README instructions, but will give GN a try.

**Comment by FullstackJack** [comment]
OK, GN build works with the recommended args and install steps in the SO question. The README for Linux should be updated with GN install steps since gyp is no longer supported.

**Comment by reiswindy** [comment]
Tried this on both Kubuntu and Linux Mint 18 and worked so far.

Supplied these values to args.gn
`is_debug = false
target_cpu = "x64"
is_component_build = true`

After compiling, ran the following commands:
`sudo mkdir -p /opt/v8/lib && sudo mkdir -p /opt/v8/include
sudo cp out.gn/x64.release/lib*.so /opt/v8/lib/ && sudo cp -R include/* /opt/v8/include
sudo cp out.gn/x64.release/natives_blob.bin /opt/v8/lib
sudo cp out.gn/x64.release/snapshot_blob.bin /opt/v8/lib
cd out.gn/x64.release/obj
ar rcsDT libv8_libplatform.a v8_libplatform/*.o
echo -e "create /opt/v8/lib/libv8_libplatform.a\naddlib /tmp/v8/out.gn/x64.release/obj/libv8_libplatform.a\nsave\nend" | sudo ar -M`

After that the usual:
`phpize
./configure --with-v8js=/opt/v8
make
make test
sudo make install`

If the lib and include files are kept on their own separate folders instead of being copied to /usr/lib and /usr/include there's no need to disable i18n it seems. Didn't throw any errors when running `php -m`.

**Comment by reiswindy** [comment]
Tried this on both Kubuntu and Linux Mint 18 and worked so far.

Supplied these values to args.gn
```
is_debug = false 
target_cpu = "x64" 
is_component_build = true
```

After compiling, ran the following commands:
```
sudo mkdir -p /opt/v8/lib && sudo mkdir -p /opt/v8/include
sudo cp out.gn/x64.release/lib*.so /opt/v8/lib/ && sudo cp -R include/* /opt/v8/include
sudo cp out.gn/x64.release/natives_blob.bin /opt/v8/lib
sudo cp out.gn/x64.release/snapshot_blob.bin /opt/v8/lib
cd out.gn/x64.release/obj
ar rcsDT libv8_libplatform.a v8_libplatform/*.o
echo -e "create /opt/v8/lib/libv8_libplatform.a\naddlib /tmp/v8/out.gn/x64.release/obj/libv8_libplatform.a\nsave\nend" | sudo ar -M`
```
Then:
```
phpize 
./configure --with-v8js=/opt/v8 
make 
make test
sudo make install
```
If the lib and include files are kept on their own separate folders instead of being copied to /usr/lib and /usr/include there's no need to disable i18n it seems. Didn't throw any errors when running `php -m`.

**Comment by temuri416** [comment]
@stesie It would be great if you could update official compile guide with the steps that we've outlined in this thread. No pressure though :)

**Comment by stesie** [comment]
@temuri416 never mind :) actually I'm already half-way through that. I've just digged a little deeper and modified `config.m4` to use the system's linker to check for `libv8_libplatform` ... which now is able to pick up the `libv8_libplatform.so` file now yielded by the GN build (instead of the .a file formerly created).

For the moment, thanks to all of you pointing out how to compile with GN :-)

**Comment by duxet** [comment]
I have prepared Docker image with v8js extension from pecl and v8 5.7 built using GN: https://github.com/Strimoid/docker-php - maybe somebody will find this useful.

**Comment by temuri416** [comment]
@duxet 

Can you possibly try check the behaviour I described here: #306 inside your docker?
