### ISSUE TITLE
ModuleLoader isn't passing the original $path

### ISSUE THREAD

**Issue by ranaharoni** [phpv8/v8js#286]
Hi there,

I just noticed that a the module loader arg for the path does not pass the real path specified in the `require` argument.

```javascript
// JS
var someInclude = require('../../components/myInclude.jsx')
...
```

```php
// PHP
...

$v8js->setModuleLoader(function($path) {
    var_dump($path); exit;
});

...
```

```php
// var_dump Output
string(25) "components/myInclude.jsx"
```

Is there any good reason it to omit the `.` and `..` from the $path argument or is it just a bug?

**Comment by AlexMasterov** [comment]
You need to write your own a loader, _ad hoc_.

[A good example](https://gist.github.com/stesie/c9143b98355295420470).

**Comment by stesie** [comment]
@ranaharoni this behaviour is caused by the "normalising" step of V8Js' require implementation.  What it tries to do is resolve relative path names (like you're trying to give) to absolute ones, so the module loader callback is provided absolute path names.

Some simple example

```js
// from root context
require('foo/bar'); // this calls the module loader with 'foo/bar'

// in foo/bar
require('./baz'); // this calls the module loader with 'foo/baz'

// still in foo/bar
require('../blar');  // this calls the module loader with 'blar'
```

So if you do *not* want that path normalisation by V8Js you need to provide some custom normalisation routine. So if you really really want no normalisation at all you can do something like

```php
$v8->setModuleNormaliser(function($basedir, $load) { return [ '', $load ]; } );
```

However generally that is a bad idea if you require modules from other modules ...
