### ISSUE TITLE
Full portable version existance?

### ISSUE THREAD

**Issue by eddr** [phpv8/v8js#367]
Hi

I'd like to know if there is a way to create such a portable package for linux?

Thanks

**Comment by stesie** [comment]
please elaborate on what you mean with "full portable".  I'm afraid, I don't get your question

**Comment by eddr** [comment]
Apologies

I mean, I'd like to simply copy a folder with all the necessary components and that it would work out of the box. No installation and stuff like that

**Comment by stesie** [comment]
No, that won't be possible since there are too many moving targets.  You have to at least match the PHP version as well as build type, i.e. zts/nts (and possibly debug/prod). Then V8 versions aren't compatible among each other so you'd have to ship V8 as well, hence update every once in a while (for security fixes, etc.) ...

So, no :)

... if you want everything pre-compiled pick one of the Docker images
