### ISSUE TITLE
How to render site with V8JS?

### ISSUE THREAD

**Issue by grandemestre** [phpv8/v8js#413]
I'm trying to understand how V8JS works, I did a test but it did not work.

I would like to render this site https://react.rocks/ to then use the DOMDocument.

So I did this:

    $url = 'https://react.rocks/';
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER,  true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $file = curl_exec($ch);
    
    $dom = new DOMDocument;
    $dom->loadHTML($file);
    $v8 = new V8Js();
    
    foreach( $dom->getElementsByTagName('script') as $script){
    
    	$v8->executeString($script->nodeValue);
    }
    $exec = file_get_contents('https://react.rocks/scripts/bundle.js');
    $v8->executeString($exec);
    
    echo $file;

I've had this return

    Uncaught exception 'V8JsScriptException' with message 'V8Js::compileString():2: ReferenceError: window is not defined' in info.php:18 Stack trace: #0 info.php(18): V8Js->executeString('var z={accessTo...') #1 {main} thrown in

**Comment by noogen** [comment]
@grandemestre like the error said `window is not defined` because you do not have the window object on the server-side.   Mostly, you can execute react stuff but not regular javascript that access window or any DOM object.  You may need something like this for react with v8js: https://github.com/reactjs/react-php-v8js

Using php v8js means you want to use both client-side and server-side to optimize your app; not simply doing every thing server-side.   Ask yourself this, "if you're just going to render everything on the server; then just use server rendering tech, why complicate things?"

**Comment by dahousecat** [comment]
Is it possible to get a javascript stack trace along with that `window is not defined` error?

Assuming there is a stack trace available to javascript when the error is first encountered, it should be possible for v8js to pass that to php?

It would be very useful when there could be one of many npm modules that could be responsible.

**Comment by stesie** [comment]
@dahousecat the V8JsScriptException exception class has a `getJsTrace` method, that should provide just that
