### ISSUE TITLE
[OFFTOPIC] Has anyone compiled v8 from source on Centos7?

### ISSUE THREAD

**Issue by temuri416** [phpv8/v8js#424]
My apologies, I just really need assistance :-)

My question is here:

https://stackoverflow.com/questions/57164363/building-v8-from-source-on-centos-7

Thank you!

**Comment by Reforced** [comment]
I did manage to compile it on a CentOS 7 machine. Biggest issue with it was that CentOS 7 comes by default with an outdated gcc (giving that GLIBC_2.18 error, the shared library wasn't found). I'd suggest updating that. I've made a wiki about it here: https://github.com/phpv8/v8js/wiki/Installing-on-CentOS-7-x64---PHP-7.3

**Comment by temuri416** [comment]
@Reforced 

Followed the steps and got this:

```
[root@centos v8]# ninja -C out.gn/x64.release/
ninja: Entering directory `out.gn/x64.release/'
[1/1] Regenerating ninja files
[88/1787] ACTION //:generate_bytecode_builtins_list(//build/toolchain/linux:clang_x64)
FAILED: gen/builtins-generated/bytecodes-builtins-list.h
python ../../tools/run.py ./bytecode_builtins_list_generator gen/builtins-generated/bytecodes-builtins-list.h
./bytecode_builtins_list_generator: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./bytecode_builtins_list_ge                                                                            nerator)
./bytecode_builtins_list_generator: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/install/v8install/v8/                                                                            out.gn/x64.release/libv8_libbase.so)
./bytecode_builtins_list_generator: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/install/v8install/v8/                                                                            out.gn/x64.release/libv8_libbase.so)
[97/1787] CXX obj/torque_base/torque-parser.o
ninja: build stopped: subcommand failed.
```

Wrong gcc version again?

**Comment by Reforced** [comment]
Seems you're moving forward! ^^ Check out the "Troubleshooting" in the Wiki. Perhaps I should just move it to the GCC section. Anyway, run as root:

```
echo "/usr/local/lib64" > /etc/ld.so.conf.d/gcc-8.3.0.x86_64.conf
ldconfig
```

to link the new glibcxx versions and you're home free! :)

**Comment by Reforced** [comment]
Did you manage to get it working? I was a bit short in my answer. Some more information. 

The error is telling the `libstdc++.so.6` library doesn't have the the right symbols. Your particular error points out v8 wants symbols from GLIBCXX_3.4.21. That [should](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) be included since GCC 5.1.0. If you have compiled the GCC from the Wiki, you should have version 8.3.0 which is compatible all the way up to GLIBCXX_3.4.25.

Now the thing is, your old library seems to be still linked. Looking at your error the library used was found in `/lib64/libstdc++.so.6`. When you run `strings /lib64/libstdc++.so.6 | grep ^GLIBCXX` it should give you all the versions in there. E.g.

![image](https://user-images.githubusercontent.com/28508541/63053777-d52ea100-bee2-11e9-9d40-a113dd534522.png)

In my answer above, you should have linked the new library and set the right export path. If not, just relink it yourself. For me it looks like:

![image](https://user-images.githubusercontent.com/28508541/63053857-0313e580-bee3-11e9-8855-430ab68daecc.png)

Cheers!

**Comment by temuri416** [comment]
Thanks, I got tied up with other things. Gonna get back to this next week.

**Comment by a-writer** [comment]
> I did manage to compile it on a CentOS 7 machine. Biggest issue with it was that CentOS 7 comes by default with an outdated gcc (giving that GLIBC_2.18 error, the shared library wasn't found). I'd suggest updating that. I've made a wiki about it here: https://github.com/phpv8/v8js/wiki/Installing-on-CentOS-7-x64---PHP-7.3

Hello,According to the information you provided, although I encountered some problems, I also compiled libv8.so successfully
(`./build/install-build-deps.sh` I can't use it normally. So try to ignore it and go to the next step, glad to succeed)

Installing php-v8js error occurred:
`./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++"  --with-php-config=/www/server/php/71/bin/php-config`
**output:**

> checking for C standard version... c++11
checking how to allow c++11 narrowing... -Wno-narrowing
checking for libv8_libplatform... found
checking for V8 version... NONE
configure: error: could not determine libv8 version

In config.log

> configure:5016: checking for libv8_libplatform
configure:5036: g++ -o conftest -Wall -Wno-write-strings -Werror  -I/opt/v8/include -std=c++11 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
configure:5036: $? = 0
configure:5038: result: found
configure:5086: checking for V8 version
configure:5114: g++ -o conftest -Wall -Wno-write-strings -Werror  -I/opt/v8/include -std=c++11 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -Wl,-rpath,/opt/v8/lib -L/opt/v8/lib -lv8  >&5
configure:5114: $? = 0
configure:5114: ./conftest
./conftest: symbol lookup error: /opt/v8/lib/libv8.so: undefined symbol: _ZN6icu_648ByteSink15GetAppendBufferEiiPciPi
configure:5114: $? = 127
configure: program exited with status 127
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""

What's the problem, please? How to solve?
