### ISSUE TITLE
The JS code contains the $symbol

### ISSUE THREAD

**Issue by ZMKing** [phpv8/v8js#443]
1. When I call a cryptographically encrypted piece of code via V8JS, the JS code has the following new syntax             
                       // Create default initializer
	                if (!subtype.hasOwnProperty('init') || this.init === subtype.init) {
	                    subtype.init = function () {
	                        subtype.$super.init.apply(this, arguments);
	                    };
	                }

	                // Initializer's prototype is the subtype object
	                subtype.init.prototype = subtype;

	                // Reference supertype
	                subtype.$super = this;

  The $super inside is js code, but PHP executes with an error. How should this kind of problem be dealt with?

2. If I want to execute js code, need to reference another JS file, then how do I handle the introduction of js file.

**Comment by stesie** [comment]
Do you have a small example php script that's ready to execute, that reproduces the crash?  I'm afraid I haven't quite understood which steps I need to take in order to reproduce the crash.

Regarding your second question, well the JS engine itself cannot access files itself. This is you need to provide its contents via PHP code yourself. Either by using the commonjs module loader feature of php-v8js, or by loading and executing the script yourself.
